import { Container, Header } from "@/shared/components/shared"
import { Metadata } from "next"

export const metadata: Metadata = {
    title: 'Undefined Pizza | Card',
    description: 'Generated by Next.js',
  }
  
  export default function CheckoutLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
    <main className="min-height-screen bg-[#F4F1EE]">
    <Container>
        <Header className="border-b-gray-200" hasSearch={false} hasCart={false}/>
        {children}
    </Container>
    </main>
    )
  }
  